### ISSUE TITLE
It does not work for python3

### ISSUE THREAD

**Issue by jufei** [lumina-networks/structifytext#1]
hi,
   Thanks for your good lib. But it does not work on Python 3.

Use your example, I got:
>>> parsed = parser.parse(output, struct)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.pyenv/versions/3.6.0/lib/python3.6/site-packages/structifytext/parser.py", line 8, in parse
    return parse_struct(six.BytesIO(text).readlines(), struct)
TypeError: a bytes-like object is required, not 'str'

If I used the six.b as below, return is None:

parsed = parser.parse(six.b(output), struct)
>>> print(parsed)
None

Thanks.

**Comment by jufei** [comment]
Thanks. The pytijo works on python3.
